services:
  - type: web
    name: smartot-command
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node backend/dist/backend/src/index.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: AI_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL_NAME
        value: llama-3.3-70b-versatile
      - key: JWT_SECRET
        generateValue: true
