import bcrypt from 'bcryptjs';
import {
  User,
  Patient,
  PatientReadiness,
  OperatingTheatre,
  Surgery,
  CSSDPack,
  CSSDItem,
  SterilizationJob,
  SterilizationCycleProfile,
  CSSDReleaseRecord,
  CSSDItemEvent,
  WorkflowEvent,
  Alert,
  PatientTransfer,
  AuditLog,
} from '../../../shared/src/types';
import { DEMO_USERS, CSSD_PACK_TYPES, OT_ROOMS } from '../../../shared/src/constants';

export async function generateSeedData() {
  const salt = bcrypt.genSaltSync(10);

  // 1. Users
  const users: User[] = DEMO_USERS.map((u) => ({
    id: u.id,
    email: u.email,
    name: u.name,
    role: u.role,
    department: u.department,
    createdAt: '2026-08-01T08:00:00Z',
  }));

  // Map password hashes for authentication
  const passwordHashes: Record<string, string> = {
    'admin@smartot.hospital': bcrypt.hashSync('Admin@123password', salt),
    'otmanager@smartot.hospital': bcrypt.hashSync('OTManager@123password', salt),
    'cssd@smartot.hospital': bcrypt.hashSync('CSSDStaff@123password', salt),
    'ward@smartot.hospital': bcrypt.hashSync('WardStaff@123password', salt),
  };

  // 2. Operating Theatres (4 Rooms)
  const operating_theatres: OperatingTheatre[] = [
    {
      id: 'ot_01',
      code: 'OT-01',
      name: 'Operating Theatre 1',
      specialty: 'General & Laparoscopic Surgery',
      currentStatus: 'SURGERY_STARTED',
      activeSurgeryId: 'surg_01',
      expectedTurnoverMinutes: 25,
      currentDelayMinutes: 0,
      riskLevel: 'LOW',
      lastUpdated: '2026-08-11T14:15:00Z',
    },
    {
      id: 'ot_02',
      code: 'OT-02',
      name: 'Operating Theatre 2',
      specialty: 'Orthopedics & Joint Replacement',
      currentStatus: 'AVAILABLE',
      expectedTurnoverMinutes: 25,
      currentDelayMinutes: 0,
      riskLevel: 'LOW',
      lastUpdated: '2026-08-11T13:50:00Z',
    },
    {
      id: 'ot_03',
      code: 'OT-03',
      name: 'Operating Theatre 3',
      specialty: 'Emergency & General Surgery',
      currentStatus: 'PREPARING',
      activeSurgeryId: 'surg_1024',
      expectedTurnoverMinutes: 25,
      currentDelayMinutes: 18,
      riskLevel: 'HIGH',
      lastUpdated: '2026-08-11T14:10:00Z',
    },
    {
      id: 'ot_04',
      code: 'OT-04',
      name: 'Operating Theatre 4',
      specialty: 'Cardiovascular & Thoracic',
      currentStatus: 'TURNOVER',
      turnoverStartedAt: '2026-08-11T13:45:00Z',
      expectedTurnoverMinutes: 25,
      currentDelayMinutes: 8,
      riskLevel: 'MEDIUM',
      lastUpdated: '2026-08-11T14:10:00Z',
    },
  ];

  // 3. Patients (22 Synthetic Patients)
  const patientData = [
    { id: 'pat_1024', mrn: 'MRN-2026-1024', name: 'Arthur Pendelton', age: 48, gender: 'M' as const, wardId: 'Ward 4B', bedNumber: 'Bed 412', diag: 'Acute Appendicitis (Scheduled for Demo Scenario)', surgeryId: 'surg_1024' },
    { id: 'pat_1001', mrn: 'MRN-2026-1001', name: 'Eleanor Sterling', age: 62, gender: 'F' as const, wardId: 'Ward 3A', bedNumber: 'Bed 301', diag: 'Cholecystitis (Laparoscopic Cholecystectomy)', surgeryId: 'surg_01' },
    { id: 'pat_1002', mrn: 'MRN-2026-1002', name: 'Thomas Thorne', age: 54, gender: 'M' as const, wardId: 'Ward 2B', bedNumber: 'Bed 205', diag: 'Right Inguinal Hernia Repair', surgeryId: 'surg_02' },
    { id: 'pat_1003', mrn: 'MRN-2026-1003', name: 'Victoria Zhao', age: 41, gender: 'F' as const, wardId: 'Ward 5C', bedNumber: 'Bed 510', diag: 'Total Knee Arthroplasty', surgeryId: 'surg_03' },
    { id: 'pat_1004', mrn: 'MRN-2026-1004', name: 'James Montgomery', age: 67, gender: 'M' as const, wardId: 'Ward 5A', bedNumber: 'Bed 502', diag: 'Coronary Artery Bypass Graft (CABG)', surgeryId: 'surg_04' },
    { id: 'pat_1005', mrn: 'MRN-2026-1005', name: 'Sophia Al-Mansoor', age: 35, gender: 'F' as const, wardId: 'Ward 4A', bedNumber: 'Bed 408', diag: 'Thyroid Lobectomy', surgeryId: 'surg_05' },
    { id: 'pat_1006', mrn: 'MRN-2026-1006', name: 'Liam O’Connor', age: 29, gender: 'M' as const, wardId: 'Ward 2A', bedNumber: 'Bed 214', diag: 'Anterior Cruciate Ligament (ACL) Reconstruction', surgeryId: 'surg_06' },
    { id: 'pat_1007', mrn: 'MRN-2026-1007', name: 'Chloe Dubois', age: 51, gender: 'F' as const, wardId: 'Ward 3B', bedNumber: 'Bed 318', diag: 'Umbilical Hernia Repair', surgeryId: 'surg_07' },
    { id: 'pat_1008', mrn: 'MRN-2026-1008', name: 'Marcus Brody', age: 58, gender: 'M' as const, wardId: 'Ward 5B', bedNumber: 'Bed 520', diag: 'Lumbar Laminectomy', surgeryId: 'surg_08' },
    { id: 'pat_1009', mrn: 'MRN-2026-1009', name: 'Aaliyah Khan', age: 44, gender: 'F' as const, wardId: 'Ward 4B', bedNumber: 'Bed 415', diag: 'Laparoscopic Hysterectomy', surgeryId: 'surg_09' },
    { id: 'pat_1010', mrn: 'MRN-2026-1010', name: 'Benjamin Hayes', age: 72, gender: 'M' as const, wardId: 'Ward 3A', bedNumber: 'Bed 306', diag: 'Transurethral Resection of Prostate (TURP)', surgeryId: 'surg_10' },
    { id: 'pat_1011', mrn: 'MRN-2026-1011', name: 'Grace Nakamura', age: 38, gender: 'F' as const, wardId: 'Ward 4A', bedNumber: 'Bed 402', diag: 'Endoscopic Sinus Surgery (FESS)', surgeryId: 'surg_11' },
    { id: 'pat_1012', mrn: 'MRN-2026-1012', name: 'Daniel Ross', age: 60, gender: 'M' as const, wardId: 'Ward 5C', bedNumber: 'Bed 514', diag: 'Total Hip Replacement', surgeryId: 'surg_12' },
    { id: 'pat_1013', mrn: 'MRN-2026-1013', name: 'Isabella Rossi', age: 49, gender: 'F' as const, wardId: 'Ward 2B', bedNumber: 'Bed 208', diag: 'Mastectomy with Sentinel Node Biopsy', surgeryId: 'surg_13' },
    { id: 'pat_1014', mrn: 'MRN-2026-1014', name: 'Ethan Wright', age: 33, gender: 'M' as const, wardId: 'Ward 4B', bedNumber: 'Bed 422', diag: 'Open Appendectomy', surgeryId: 'surg_14' },
    { id: 'pat_1015', mrn: 'MRN-2026-1015', name: 'Maya Patel', age: 56, gender: 'F' as const, wardId: 'Ward 3B', bedNumber: 'Bed 312', diag: 'Carotid Endarterectomy', surgeryId: 'surg_15' },
    { id: 'pat_1016', mrn: 'MRN-2026-1016', name: 'Lucas Silva', age: 24, gender: 'M' as const, wardId: 'Ward 2A', bedNumber: 'Bed 218', diag: 'Shoulder Arthroscopy', surgeryId: 'surg_16' },
    { id: 'pat_1017', mrn: 'MRN-2026-1017', name: 'Zoe Washington', age: 69, gender: 'F' as const, wardId: 'Ward 5A', bedNumber: 'Bed 508', diag: 'Aortic Valve Replacement', surgeryId: 'surg_17' },
    { id: 'pat_1018', mrn: 'MRN-2026-1018', name: 'Henry Cavendish', age: 75, gender: 'M' as const, wardId: 'Ward 3A', bedNumber: 'Bed 315', diag: 'Femoral-Popliteal Bypass', surgeryId: 'surg_18' },
    { id: 'pat_1019', mrn: 'MRN-2026-1019', name: 'Amelia Earhart', age: 46, gender: 'F' as const, wardId: 'Ward 4C', bedNumber: 'Bed 430', diag: 'Cataract Phacoemulsification', surgeryId: 'surg_19' },
    { id: 'pat_1020', mrn: 'MRN-2026-1020', name: 'Oliver Twist', age: 31, gender: 'M' as const, wardId: 'Ward 2B', bedNumber: 'Bed 220', diag: 'Laparoscopic Appendectomy', surgeryId: 'surg_20' },
  ];

  const patients: Patient[] = [];
  const patient_readiness: PatientReadiness[] = [];

  patientData.forEach((p, idx) => {
    // For P-1024 (Demo scenario target), set consent MISSING initially
    const isTarget = p.id === 'pat_1024';
    const consentStatus = isTarget ? 'MISSING' : idx % 7 === 0 ? 'PENDING' : 'VERIFIED';
    const admissionDone = true;
    const docDone = !isTarget && idx % 9 !== 0;
    const reportsDone = true;
    const docConfirmed = !isTarget;
    const preopDone = !isTarget;

    const completedCount =
      (admissionDone ? 1 : 0) +
      (consentStatus === 'VERIFIED' ? 1 : 0) +
      (docDone ? 1 : 0) +
      (reportsDone ? 1 : 0) +
      (docConfirmed ? 1 : 0) +
      (preopDone ? 1 : 0);

    const isReady = completedCount === 6;

    patients.push({
      id: p.id,
      mrn: p.mrn,
      name: p.name,
      age: p.age,
      gender: p.gender,
      wardId: p.wardId,
      bedNumber: p.bedNumber,
      admissionDate: '2026-08-11T07:30:00Z',
      status: isTarget ? 'PREPARING' : isReady ? 'READY_FOR_OT' : 'PREPARING',
      primaryDiagnosis: p.diag,
      activeSurgeryId: p.surgeryId,
    });

    patient_readiness.push({
      id: `readiness_${p.id}`,
      patientId: p.id,
      admissionCompleted: admissionDone,
      consentStatus: consentStatus,
      documentationCompleted: docDone,
      reportsAvailable: reportsDone,
      doctorConfirmed: docConfirmed,
      preopPrepCompleted: preopDone,
      completedItemsCount: completedCount,
      totalItemsCount: 6,
      isReady: isReady,
      notes: isTarget ? 'Awaiting surgical consent confirmation from ward attending' : 'Pre-op checklist verification in progress',
      updatedAt: '2026-08-11T13:40:00Z',
    });
  });

  // 4. Surgeries (21 Surgeries linked to OTs and Patients)
  const surgeries: Surgery[] = [
    {
      id: 'surg_1024',
      patientId: 'pat_1024',
      patientName: 'Arthur Pendelton',
      patientMrn: 'MRN-2026-1024',
      otId: 'ot_03',
      otCode: 'OT-03',
      procedureName: 'Emergency Appendectomy',
      surgeonName: 'Dr. Robert Martinez',
      anesthesiologistName: 'Dr. Clara Oswald',
      requiredPackType: 'Appendectomy Set',
      scheduledStartTime: '2026-08-11T14:00:00Z',
      expectedDurationMinutes: 60,
      status: 'SCHEDULED',
      delayMinutes: 18,
      delayReason: 'Missing patient surgical consent and delayed pre-op checklist completion in Ward 4B',
      riskLevel: 'HIGH',
      riskReasons: [
        'Surgical consent status currently MISSING',
        'Patient readiness checklist is 5/6 (Incomplete)',
        'Scheduled OT start time has elapsed by 18 minutes',
      ],
      createdAt: '2026-08-11T08:00:00Z',
    },
    {
      id: 'surg_01',
      patientId: 'pat_1001',
      patientName: 'Eleanor Sterling',
      patientMrn: 'MRN-2026-1001',
      otId: 'ot_01',
      otCode: 'OT-01',
      procedureName: 'Laparoscopic Cholecystectomy',
      surgeonName: 'Dr. Alan Grant',
      anesthesiologistName: 'Dr. Ian Malcolm',
      requiredPackType: 'Laparotomy Major Set',
      assignedPackId: 'CSSD-004',
      scheduledStartTime: '2026-08-11T13:30:00Z',
      actualStartTime: '2026-08-11T13:35:00Z',
      expectedDurationMinutes: 75,
      status: 'IN_PROGRESS',
      delayMinutes: 5,
      riskLevel: 'LOW',
      createdAt: '2026-08-11T08:00:00Z',
    },
    {
      id: 'surg_02',
      patientId: 'pat_1002',
      patientName: 'Thomas Thorne',
      patientMrn: 'MRN-2026-1002',
      otId: 'ot_01',
      otCode: 'OT-01',
      procedureName: 'Right Inguinal Hernia Repair',
      surgeonName: 'Dr. Alan Grant',
      anesthesiologistName: 'Dr. Ian Malcolm',
      requiredPackType: 'Laparotomy Major Set',
      scheduledStartTime: '2026-08-11T15:30:00Z',
      expectedDurationMinutes: 60,
      status: 'SCHEDULED',
      delayMinutes: 0,
      riskLevel: 'LOW',
      createdAt: '2026-08-11T08:00:00Z',
    },
    {
      id: 'surg_03',
      patientId: 'pat_1003',
      patientName: 'Victoria Zhao',
      patientMrn: 'MRN-2026-1003',
      otId: 'ot_02',
      otCode: 'OT-02',
      procedureName: 'Total Knee Arthroplasty',
      surgeonName: 'Dr. Gregory House',
      anesthesiologistName: 'Dr. Lisa Cuddy',
      requiredPackType: 'Orthopedic Arthroplasty Set',
      scheduledStartTime: '2026-08-11T14:30:00Z',
      expectedDurationMinutes: 110,
      status: 'READY',
      delayMinutes: 0,
      riskLevel: 'LOW',
      createdAt: '2026-08-11T08:00:00Z',
    },
    {
      id: 'surg_04',
      patientId: 'pat_1004',
      patientName: 'James Montgomery',
      patientMrn: 'MRN-2026-1004',
      otId: 'ot_04',
      otCode: 'OT-04',
      procedureName: 'Coronary Artery Bypass Graft (CABG)',
      surgeonName: 'Dr. Cristina Yang',
      anesthesiologistName: 'Dr. Derek Shepherd',
      requiredPackType: 'Cardiovascular Basic Set',
      scheduledStartTime: '2026-08-11T15:00:00Z',
      expectedDurationMinutes: 180,
      status: 'SCHEDULED',
      delayMinutes: 12,
      delayReason: 'Turnover in OT-04 running over benchmark by 12 minutes',
      riskLevel: 'MEDIUM',
      riskReasons: ['OT-04 turnover delayed past 25-minute benchmark', 'Cascading schedule push for subsequent case'],
      createdAt: '2026-08-11T08:00:00Z',
    },
    {
      id: 'surg_05',
      patientId: 'pat_1005',
      patientName: 'Sophia Al-Mansoor',
      patientMrn: 'MRN-2026-1005',
      otId: 'ot_03',
      otCode: 'OT-03',
      procedureName: 'Thyroid Lobectomy',
      surgeonName: 'Dr. Robert Martinez',
      anesthesiologistName: 'Dr. Clara Oswald',
      requiredPackType: 'Laparotomy Major Set',
      scheduledStartTime: '2026-08-11T16:00:00Z',
      expectedDurationMinutes: 70,
      status: 'SCHEDULED',
      delayMinutes: 20,
      riskLevel: 'MEDIUM',
      riskReasons: ['Downstream delay inherited from earlier case (P-1024) in OT-03'],
      createdAt: '2026-08-11T08:00:00Z',
    },
  ];

  // 5. CSSD Instrument Packs (32 Packs with QR identifiers)
  const cssd_packs: CSSDPack[] = [
    // Target Pack for Demo Scenario
    {
      id: 'pack_021',
      packId: 'CSSD-021',
      packType: 'Appendectomy Set',
      sterilizationBatch: 'BATCH-20260810-03',
      sterilizedAt: '2026-08-10T11:00:00Z',
      expiresAt: '2026-08-24T11:00:00Z',
      sterilityStatus: 'STERILIZED',
      currentStatus: 'AVAILABLE',
      currentLocation: 'CSSD Sterile Storage Shelf A-3',
      notes: 'Passed biological and chemical indicator verification',
      updatedAt: '2026-08-10T11:30:00Z',
    },
    // Expired Pack for Error/Validation testing
    {
      id: 'pack_099',
      packId: 'CSSD-099',
      packType: 'Appendectomy Set',
      sterilizationBatch: 'BATCH-20260715-01',
      sterilizedAt: '2026-07-15T09:00:00Z',
      expiresAt: '2026-07-29T09:00:00Z', // Expired!
      sterilityStatus: 'EXPIRED',
      currentStatus: 'EXPIRED',
      currentLocation: 'CSSD Quarantine Area',
      notes: 'Expired sterile barrier pack. Reprocessing required.',
      updatedAt: '2026-08-01T09:00:00Z',
    },
    // Unsterilized/Reprocessing Pack
    {
      id: 'pack_044',
      packId: 'CSSD-044',
      packType: 'Laparotomy Major Set',
      sterilizationBatch: 'BATCH-20260811-09',
      sterilizedAt: '2026-08-11T13:00:00Z',
      expiresAt: '2026-08-25T13:00:00Z',
      sterilityStatus: 'UNSTERILIZED',
      currentStatus: 'STERILIZING',
      currentLocation: 'Autoclave Chamber #2',
      notes: 'Undergoing 134°C steam sterilization cycle',
      updatedAt: '2026-08-11T13:30:00Z',
    },
    {
      id: 'pack_001',
      packId: 'CSSD-001',
      packType: 'Laparotomy Major Set',
      sterilizationBatch: 'BATCH-20260810-01',
      sterilizedAt: '2026-08-10T08:00:00Z',
      expiresAt: '2026-08-24T08:00:00Z',
      sterilityStatus: 'STERILIZED',
      currentStatus: 'AVAILABLE',
      currentLocation: 'CSSD Main Storage Shelf B-1',
      updatedAt: '2026-08-10T08:45:00Z',
    },
    {
      id: 'pack_002',
      packId: 'CSSD-002',
      packType: 'Orthopedic Arthroplasty Set',
      sterilizationBatch: 'BATCH-20260810-02',
      sterilizedAt: '2026-08-10T09:30:00Z',
      expiresAt: '2026-08-24T09:30:00Z',
      sterilityStatus: 'STERILIZED',
      currentStatus: 'STORED',
      currentLocation: 'CSSD Main Storage Shelf C-2',
      updatedAt: '2026-08-10T10:00:00Z',
    },
    {
      id: 'pack_003',
      packId: 'CSSD-003',
      packType: 'Cardiovascular Basic Set',
      sterilizationBatch: 'BATCH-20260809-04',
      sterilizedAt: '2026-08-09T14:00:00Z',
      expiresAt: '2026-08-23T14:00:00Z',
      sterilityStatus: 'STERILIZED',
      currentStatus: 'AVAILABLE',
      currentLocation: 'CSSD Main Storage Shelf D-1',
      updatedAt: '2026-08-09T14:30:00Z',
    },
    {
      id: 'pack_004',
      packId: 'CSSD-004',
      packType: 'Laparotomy Major Set',
      sterilizationBatch: 'BATCH-20260810-01',
      sterilizedAt: '2026-08-10T08:00:00Z',
      expiresAt: '2026-08-24T08:00:00Z',
      sterilityStatus: 'STERILIZED',
      currentStatus: 'IN_USE',
      currentLocation: 'OT-01 Sterile Field',
      assignedOtId: 'ot_01',
      assignedSurgeryId: 'surg_01',
      updatedAt: '2026-08-11T13:30:00Z',
    },
    {
      id: 'pack_005',
      packId: 'CSSD-005',
      packType: 'Appendectomy Set',
      sterilizationBatch: 'BATCH-20260810-03',
      sterilizedAt: '2026-08-10T11:00:00Z',
      expiresAt: '2026-08-24T11:00:00Z',
      sterilityStatus: 'STERILIZED',
      currentStatus: 'STORED',
      currentLocation: 'CSSD Main Storage Shelf A-2',
      updatedAt: '2026-08-10T11:45:00Z',
    },
    {
      id: 'pack_006',
      packId: 'CSSD-006',
      packType: 'Orthopedic Arthroplasty Set',
      sterilizationBatch: 'BATCH-20260811-01',
      sterilizedAt: '2026-08-11T06:00:00Z',
      expiresAt: '2026-08-25T06:00:00Z',
      sterilityStatus: 'STERILIZED',
      currentStatus: 'AVAILABLE',
      currentLocation: 'CSSD Main Storage Shelf C-1',
      updatedAt: '2026-08-11T06:40:00Z',
    },
  ];

  // Populate remaining packs up to 32
  const typesList = [...CSSD_PACK_TYPES];
  for (let i = 7; i <= 32; i++) {
    const pad = i.toString().padStart(3, '0');
    const packType = typesList[i % typesList.length];
    const isReproc = i % 5 === 0;
    const isSterilizing = i % 6 === 0;

    cssd_packs.push({
      id: `pack_${pad}`,
      packId: `CSSD-${pad}`,
      packType: packType,
      sterilizationBatch: `BATCH-20260810-${(i % 5) + 1}`,
      sterilizedAt: '2026-08-10T08:00:00Z',
      expiresAt: '2026-08-24T08:00:00Z',
      sterilityStatus: isReproc ? 'UNSTERILIZED' : 'STERILIZED',
      currentStatus: isReproc ? 'REPROCESSING' : isSterilizing ? 'STERILIZING' : 'AVAILABLE',
      currentLocation: isReproc ? 'CSSD Decontamination Bay' : 'CSSD Main Storage',
      updatedAt: '2026-08-11T08:00:00Z',
    });
  }

  // 6. Active Alerts (Operational Warnings)
  const alerts: Alert[] = [
    {
      id: 'alt_01',
      severity: 'CRITICAL',
      title: 'Missing Surgical Consent: Patient P-1024',
      description: 'Scheduled surgery "Emergency Appendectomy" in OT-03 is 18m past schedule start with Consent MISSING in Ward 4B.',
      entityType: 'PATIENT',
      entityId: 'pat_1024',
      responsibleRole: 'WARD_STAFF',
      recommendedAction: 'Verify patient/surrogate consent immediately in Pre-Op Ward 4B or alert attending surgeon.',
      status: 'OPEN',
      createdAt: '2026-08-11T13:45:00Z',
    },
    {
      id: 'alt_02',
      severity: 'WARNING',
      title: 'Turnover Benchmark Overrun: OT-04',
      description: 'Room turnover in OT-04 has exceeded the 25-minute benchmark by 12 minutes, placing CABG case (surg_04) at delay risk.',
      entityType: 'OT',
      entityId: 'ot_04',
      responsibleRole: 'OT_MANAGER',
      recommendedAction: 'Dispatch auxiliary environmental services team to accelerate terminal disinfection.',
      status: 'OPEN',
      createdAt: '2026-08-11T14:02:00Z',
    },
    {
      id: 'alt_03',
      severity: 'INFO',
      title: 'CSSD Demand Advisory: Appendectomy Sets',
      description: 'Tomorrow has 8 scheduled appendectomy procedures with only 5 sets currently sterilized and available.',
      entityType: 'CSSD_PACK',
      entityId: 'Appendectomy Set',
      responsibleRole: 'CSSD_STAFF',
      recommendedAction: 'Prioritize sterilization batch #4 for incoming decontaminated appendectomy trays.',
      status: 'OPEN',
      createdAt: '2026-08-11T12:00:00Z',
    },
  ];

  // 7. Workflow Events (Correlated Event Stream)
  const workflow_events: WorkflowEvent[] = [
    {
      id: 'evt_001',
      eventType: 'PATIENT_ADMITTED',
      entityType: 'PATIENT',
      entityId: 'pat_1024',
      department: 'ADMISSIONS',
      timestamp: '2026-08-11T07:30:00Z',
      actorId: 'usr_ward_01',
      actorName: 'Nurse David Chen',
      metadata: { mrn: 'MRN-2026-1024', ward: 'Ward 4B', diagnosis: 'Acute Appendicitis' },
    },
    {
      id: 'evt_002',
      eventType: 'SURGERY_SCHEDULED',
      entityType: 'SURGERY',
      entityId: 'surg_1024',
      department: 'OT',
      timestamp: '2026-08-11T08:00:00Z',
      actorId: 'usr_ot_01',
      actorName: 'Marcus Vance, RN',
      metadata: { otCode: 'OT-03', scheduledStartTime: '2026-08-11T14:00:00Z', requiredPack: 'Appendectomy Set' },
    },
    {
      id: 'evt_003',
      eventType: 'CSSD_PACK_STERILIZED',
      entityType: 'CSSD_PACK',
      entityId: 'CSSD-021',
      department: 'CSSD',
      timestamp: '2026-08-10T11:00:00Z',
      actorId: 'usr_cssd_01',
      actorName: 'Elena Rostova',
      metadata: { batch: 'BATCH-20260810-03', packType: 'Appendectomy Set', expiry: '2026-08-24T11:00:00Z' },
    },
    {
      id: 'evt_004',
      eventType: 'ALERT_TRIGGERED',
      entityType: 'ALERT',
      entityId: 'alt_01',
      department: 'SYSTEM',
      timestamp: '2026-08-11T13:45:00Z',
      actorId: 'system',
      actorName: 'SmartOT Alert Engine',
      metadata: { patientId: 'pat_1024', triggerReason: 'Consent MISSING 15m prior to scheduled OT start' },
    },
    {
      id: 'evt_005',
      eventType: 'SURGERY_STARTED',
      entityType: 'SURGERY',
      entityId: 'surg_01',
      department: 'OT',
      timestamp: '2026-08-11T13:35:00Z',
      actorId: 'usr_ot_01',
      actorName: 'Marcus Vance, RN',
      metadata: { otCode: 'OT-01', patientId: 'pat_1001', packId: 'CSSD-004' },
    },
    {
      id: 'evt_006',
      eventType: 'TURNOVER_STARTED',
      entityType: 'OT',
      entityId: 'ot_04',
      department: 'OT',
      timestamp: '2026-08-11T13:45:00Z',
      actorId: 'usr_ot_01',
      actorName: 'Marcus Vance, RN',
      metadata: { expectedMinutes: 25 },
    },
    {
      id: 'evt_007',
      eventType: 'TURNOVER_DELAY_DETECTED',
      entityType: 'OT',
      entityId: 'ot_04',
      department: 'SYSTEM',
      timestamp: '2026-08-11T14:10:00Z',
      actorId: 'system',
      actorName: 'SmartOT Delay Engine',
      metadata: { delayMinutes: 12, cause: 'TURNOVER_OVERRUN' },
    },
  ];

  // 8. Transfers
  const transfers: PatientTransfer[] = [
    {
      id: 'trf_01',
      patientId: 'pat_1001',
      surgeryId: 'surg_01',
      fromWard: 'Ward 3A',
      toOtId: 'ot_01',
      toOtCode: 'OT-01',
      transferStartedAt: '2026-08-11T13:10:00Z',
      patientArrivedAt: '2026-08-11T13:22:00Z',
      durationMinutes: 12,
      status: 'COMPLETED',
    },
  ];

  // 9. Audit Logs
  const audit_logs: AuditLog[] = [
    {
      id: 'aud_01',
      timestamp: '2026-08-11T08:00:00Z',
      actorId: 'usr_admin_01',
      actorName: 'Dr. Sarah Jenkins',
      action: 'SYSTEM_INITIALIZATION',
      entityType: 'SYSTEM',
      entityId: 'smartot_core',
      previousState: null,
      newState: { status: 'INITIALIZED', seedVersion: '1.0.0' },
      ipAddress: '127.0.0.1',
    },
    {
      id: 'aud_02',
      timestamp: '2026-08-11T08:05:00Z',
      actorId: 'usr_ot_01',
      actorName: 'Marcus Vance, RN',
      action: 'OT_SCHEDULE_PUBLISHED',
      entityType: 'OT_SCHEDULE',
      entityId: 'schedule_20260811',
      previousState: null,
      newState: { caseCount: 6, otCount: 4 },
      ipAddress: '10.0.4.12',
    },
  ];

  // 10. CSSD Cycle Profiles
  const cssd_cycle_profiles: SterilizationCycleProfile[] = [
    {
      id: 'cp_01',
      method: 'Steam Autoclave Standard (134°C)',
      cycleName: 'Steam Standard 134C',
      expectedDurationMinutes: 45,
      preparationDurationMinutes: 10,
      processingDurationMinutes: 25,
      coolingDurationMinutes: 10,
      totalExpectedDurationMinutes: 45,
    },
    {
      id: 'cp_02',
      method: 'Ethylene Oxide (ETO) Low Temp',
      cycleName: 'ETO Low Temp 55C',
      expectedDurationMinutes: 240,
      preparationDurationMinutes: 30,
      processingDurationMinutes: 180,
      coolingDurationMinutes: 30,
      totalExpectedDurationMinutes: 240,
    },
    {
      id: 'cp_03',
      method: 'Hydrogen Peroxide Vapor (VHP / Plasma)',
      cycleName: 'VHP Low Temp Sterilization',
      expectedDurationMinutes: 35,
      preparationDurationMinutes: 5,
      processingDurationMinutes: 25,
      coolingDurationMinutes: 5,
      totalExpectedDurationMinutes: 35,
    },
    {
      id: 'cp_04',
      method: 'Dry Heat Sterilization',
      cycleName: 'Dry Heat 160C',
      expectedDurationMinutes: 120,
      preparationDurationMinutes: 15,
      processingDurationMinutes: 90,
      coolingDurationMinutes: 15,
      totalExpectedDurationMinutes: 120,
    },
  ];

  // 11. CSSD Items (Data-Driven Master Catalog)
  const now = new Date();
  const cssd_items: CSSDItem[] = [
    {
      id: 'item_021',
      name: 'Orthopedic Major Instrument Set',
      qrCode: 'SET-021',
      category: 'Instrument Set',
      quantity: 1,
      location: 'CSSD Sterile Store Shelf A-3',
      currentStatus: 'STERILE',
      lastSterilizedAt: new Date(now.getTime() - 3 * 3600000).toISOString(),
      sterilizationMethod: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-101',
      condition: 'EXCELLENT',
      releasedBy: 'CSSD Supervisor - Sarah Connor',
      releasedAt: new Date(now.getTime() - 2.5 * 3600000).toISOString(),
      manufacturer: 'Aesculap',
      model: 'ORTHO-MAX-200',
      serialNumber: 'SN-998811',
      assignedOtId: 'ot_03',
      assignedSurgeryId: 'surg_1024',
      notes: 'Certified sterile set pre-assigned to OT-03 Appendectomy procedure.',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'item_104',
      name: 'Major Laparotomy Retractor Set',
      qrCode: 'INS-104',
      category: 'Surgical Instrument',
      quantity: 2,
      location: 'CSSD Intake Decontamination Bay',
      currentStatus: 'QUEUED',
      condition: 'GOOD',
      manufacturer: 'Integra LifeSciences',
      model: 'RETRACT-90',
      serialNumber: 'SN-123441',
      assignedOtId: 'ot_03',
      assignedSurgeryId: 'surg_1024',
      notes: 'Waiting for active autoclave chamber load.',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'item_005',
      name: 'Vascular Bypass Surgical Tray',
      qrCode: 'TRAY-005',
      category: 'Surgical Tray',
      quantity: 1,
      location: 'Autoclave Chamber #1',
      currentStatus: 'PROCESSING',
      sterilizationMethod: 'Hydrogen Peroxide Vapor (VHP / Plasma)',
      cycleReference: 'CYC-PLASMA-04',
      condition: 'EXCELLENT',
      manufacturer: 'Sklar Instruments',
      model: 'VASC-PRO-4',
      serialNumber: 'SN-443312',
      notes: 'Currently undergoing active VHP low-temperature cycle.',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'item_002',
      name: 'Flexible Video Bronchoscope',
      qrCode: 'END-002',
      category: 'Endoscopy Equipment',
      quantity: 1,
      location: 'CSSD Intake Bay',
      currentStatus: 'RETURNED_TO_CSSD',
      condition: 'FAIR',
      manufacturer: 'Olympus',
      model: 'BF-1TH190',
      serialNumber: 'SN-OL-7781',
      notes: 'Returned from OT-04 post-procedure. Requires high-level disinfection.',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'item_012',
      name: 'Harmonic Scalpel Handpiece',
      qrCode: 'DEV-012',
      category: 'Reusable Device',
      quantity: 1,
      location: 'Verification & Release Bench',
      currentStatus: 'RELEASE_PENDING',
      sterilizationMethod: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-105',
      condition: 'EXCELLENT',
      manufacturer: 'Ethicon',
      model: 'HARMONIC-HP',
      serialNumber: 'SN-ETH-0991',
      notes: 'Autoclave complete. Waiting for biological indicator verification check.',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'item_088',
      name: 'Micro-Vascular Scissors Set',
      qrCode: 'INS-088',
      category: 'Metal Instrument',
      quantity: 1,
      location: 'CSSD Quarantine Bay Q-2',
      currentStatus: 'QUARANTINED',
      sterilizationMethod: 'Ethylene Oxide (ETO) Low Temp',
      cycleReference: 'CYC-ETO-002',
      condition: 'DAMAGED',
      manufacturer: 'Storz',
      model: 'MICRO-SCISSOR-V2',
      serialNumber: 'SN-STZ-4411',
      releasedBy: 'QA Inspector - Elena Rostova',
      releasedAt: new Date(now.getTime() - 1 * 3600000).toISOString(),
      notes: 'Quarantined due to compromised sterile packaging barrier.',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'item_009',
      name: 'Neuro Craniotomy Specialty Tray',
      qrCode: 'SET-009',
      category: 'Specialized Instrument',
      quantity: 1,
      location: 'CSSD Sterile Storage Shelf B-2',
      currentStatus: 'STERILE',
      lastSterilizedAt: new Date(now.getTime() - 6 * 3600000).toISOString(),
      sterilizationMethod: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-099',
      condition: 'EXCELLENT',
      releasedBy: 'CSSD Supervisor - Sarah Connor',
      releasedAt: new Date(now.getTime() - 5.5 * 3600000).toISOString(),
      manufacturer: 'Codman',
      model: 'NEURO-CRAN-X',
      serialNumber: 'SN-COD-8822',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'item_014',
      name: 'Cardiac Surgery Bypass Master Set',
      qrCode: 'SET-014',
      category: 'Instrument Set',
      quantity: 1,
      location: 'OT-04 Surgical Suite',
      currentStatus: 'IN_USE',
      lastSterilizedAt: new Date(now.getTime() - 4 * 3600000).toISOString(),
      sterilizationMethod: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-100',
      condition: 'EXCELLENT',
      assignedOtId: 'ot_04',
      assignedSurgeryId: 'surg_04',
      createdAt: '2026-08-01T08:00:00Z',
      updatedAt: new Date().toISOString(),
    },
  ];

  // 12. Sterilization Jobs
  const cssd_sterilization_jobs: SterilizationJob[] = [
    {
      id: 'job_101',
      jobId: 'J-101',
      instrumentId: 'item_021',
      instrumentName: 'Orthopedic Major Instrument Set',
      qrCode: 'SET-021',
      quantity: 1,
      sourceDepartment: 'Central CSSD',
      sourceOT: 'OT-03',
      associatedSurgeryId: 'surg_1024',
      associatedSurgeryName: 'Acute Appendectomy',
      submittedBy: 'Nurse Ellen Ripley',
      submittedAt: new Date(now.getTime() - 4 * 3600000).toISOString(),
      receivedBy: 'CSSD Technician Tom',
      receivedAt: new Date(now.getTime() - 3.8 * 3600000).toISOString(),
      status: 'RELEASED',
      method: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-101',
      processingStartedAt: new Date(now.getTime() - 3.5 * 3600000).toISOString(),
      expectedCompletionAt: new Date(now.getTime() - 2.75 * 3600000).toISOString(),
      processingCompletedAt: new Date(now.getTime() - 2.75 * 3600000).toISOString(),
      releasedAt: new Date(now.getTime() - 2.5 * 3600000).toISOString(),
      releasedBy: 'CSSD Supervisor - Sarah Connor',
      notes: 'Cycle completed cleanly. Passed biological and chemical indicators.',
      createdAt: new Date(now.getTime() - 4 * 3600000).toISOString(),
      updatedAt: new Date(now.getTime() - 2.5 * 3600000).toISOString(),
    },
    {
      id: 'job_102',
      jobId: 'J-102',
      instrumentId: 'item_104',
      instrumentName: 'Major Laparotomy Retractor Set',
      qrCode: 'INS-104',
      quantity: 2,
      sourceDepartment: 'OT-03',
      sourceOT: 'OT-03',
      associatedSurgeryId: 'surg_1024',
      associatedSurgeryName: 'Acute Appendectomy',
      submittedBy: 'OT-03 Scrub Tech',
      submittedAt: new Date(now.getTime() - 45 * 60000).toISOString(),
      receivedBy: 'CSSD Technician Tom',
      receivedAt: new Date(now.getTime() - 30 * 60000).toISOString(),
      status: 'QUEUED',
      method: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-106',
      notes: 'Awaiting batch load in Autoclave Chamber #2.',
      createdAt: new Date(now.getTime() - 45 * 60000).toISOString(),
      updatedAt: new Date(now.getTime() - 30 * 60000).toISOString(),
    },
    {
      id: 'job_103',
      jobId: 'J-103',
      instrumentId: 'item_005',
      instrumentName: 'Vascular Bypass Surgical Tray',
      qrCode: 'TRAY-005',
      quantity: 1,
      sourceDepartment: 'OT-04',
      sourceOT: 'OT-04',
      submittedBy: 'Circulating Nurse Johnson',
      submittedAt: new Date(now.getTime() - 30 * 60000).toISOString(),
      receivedBy: 'CSSD Specialist Adams',
      receivedAt: new Date(now.getTime() - 25 * 60000).toISOString(),
      status: 'PROCESSING',
      method: 'Hydrogen Peroxide Vapor (VHP / Plasma)',
      cycleReference: 'CYC-PLASMA-04',
      processingStartedAt: new Date(now.getTime() - 15 * 60000).toISOString(),
      expectedCompletionAt: new Date(now.getTime() + 20 * 60000).toISOString(), // 20m remaining!
      notes: 'Active VHP plasma cycle in progress.',
      createdAt: new Date(now.getTime() - 30 * 60000).toISOString(),
      updatedAt: new Date(now.getTime() - 15 * 60000).toISOString(),
    },
    {
      id: 'job_104',
      jobId: 'J-104',
      instrumentId: 'item_012',
      instrumentName: 'Harmonic Scalpel Handpiece',
      qrCode: 'DEV-012',
      quantity: 1,
      sourceDepartment: 'OT-01',
      sourceOT: 'OT-01',
      submittedBy: 'Dr. Alan Grant',
      submittedAt: new Date(now.getTime() - 90 * 60000).toISOString(),
      receivedBy: 'CSSD Specialist Adams',
      receivedAt: new Date(now.getTime() - 80 * 60000).toISOString(),
      status: 'RELEASE_PENDING',
      method: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-105',
      processingStartedAt: new Date(now.getTime() - 55 * 60000).toISOString(),
      expectedCompletionAt: new Date(now.getTime() - 10 * 60000).toISOString(),
      processingCompletedAt: new Date(now.getTime() - 8 * 60000).toISOString(),
      notes: 'Autoclave phase done. Pending release verification signature.',
      createdAt: new Date(now.getTime() - 90 * 60000).toISOString(),
      updatedAt: new Date(now.getTime() - 8 * 60000).toISOString(),
    },
    {
      id: 'job_105',
      jobId: 'J-105',
      instrumentId: 'item_088',
      instrumentName: 'Micro-Vascular Scissors Set',
      qrCode: 'INS-088',
      quantity: 1,
      sourceDepartment: 'CSSD QA',
      submittedBy: 'CSSD Technician Tom',
      submittedAt: new Date(now.getTime() - 3 * 3600000).toISOString(),
      receivedBy: 'QA Inspector - Elena Rostova',
      receivedAt: new Date(now.getTime() - 2.8 * 3600000).toISOString(),
      status: 'QUARANTINED',
      method: 'Ethylene Oxide (ETO) Low Temp',
      cycleReference: 'CYC-ETO-002',
      processingStartedAt: new Date(now.getTime() - 2.5 * 3600000).toISOString(),
      processingCompletedAt: new Date(now.getTime() - 1.2 * 3600000).toISOString(),
      releasedBy: 'QA Inspector - Elena Rostova',
      releasedAt: new Date(now.getTime() - 1 * 3600000).toISOString(),
      rejectionReason: 'Pouch seal compromised during pressure change.',
      notes: 'Pouch integrity check failed. Item quarantined for repackaging.',
      createdAt: new Date(now.getTime() - 3 * 3600000).toISOString(),
      updatedAt: new Date(now.getTime() - 1 * 3600000).toISOString(),
    },
    {
      id: 'job_106',
      jobId: 'J-106',
      instrumentId: 'item_009',
      instrumentName: 'Orthopedic Joint Replacement Kit',
      qrCode: 'SET-009',
      quantity: 1,
      sourceDepartment: 'OT-02',
      sourceOT: 'OT-02',
      submittedBy: 'Scrub Nurse Clara',
      submittedAt: new Date(now.getTime() - 20 * 60000).toISOString(),
      receivedBy: 'CSSD Specialist Adams',
      receivedAt: new Date(now.getTime() - 15 * 60000).toISOString(),
      status: 'PROCESSING',
      method: 'Steam Autoclave Standard (134°C)',
      cycleReference: 'CYC-STEAM-108',
      processingStartedAt: new Date(now.getTime() - 10 * 60000).toISOString(),
      expectedCompletionAt: new Date(now.getTime() + 28 * 60000).toISOString(),
      notes: 'High-temperature steam sterilization in progress inside Chamber #3.',
      createdAt: new Date(now.getTime() - 20 * 60000).toISOString(),
      updatedAt: new Date(now.getTime() - 10 * 60000).toISOString(),
    },
    {
      id: 'job_107',
      jobId: 'J-107',
      instrumentId: 'item_014',
      instrumentName: 'Laparoscopic Cholecystectomy Specialty Set',
      qrCode: 'SET-014',
      quantity: 1,
      sourceDepartment: 'OT-01',
      sourceOT: 'OT-01',
      submittedBy: 'Nurse Marcus Vance',
      submittedAt: new Date(now.getTime() - 15 * 60000).toISOString(),
      receivedBy: 'CSSD Specialist Adams',
      receivedAt: new Date(now.getTime() - 10 * 60000).toISOString(),
      status: 'PROCESSING',
      method: 'Ethylene Oxide (ETO) Low Temp',
      cycleReference: 'CYC-ETO-005',
      processingStartedAt: new Date(now.getTime() - 5 * 60000).toISOString(),
      expectedCompletionAt: new Date(now.getTime() + 42 * 60000).toISOString(),
      notes: 'Low-temperature ETO cycle active in Chamber #4.',
      createdAt: new Date(now.getTime() - 15 * 60000).toISOString(),
      updatedAt: new Date(now.getTime() - 5 * 60000).toISOString(),
    },
  ];

  // 13. CSSD Release Records
  const cssd_releases: CSSDReleaseRecord[] = [
    {
      id: 'rel_101',
      jobId: 'J-101',
      instrumentId: 'item_021',
      cycleCompleted: true,
      packagingAcceptable: true,
      indicatorVerified: true,
      releaseDecision: 'RELEASED',
      notes: 'All 3 sterile verification criteria passed.',
      releasedBy: 'CSSD Supervisor - Sarah Connor',
      releasedAt: new Date(now.getTime() - 2.5 * 3600000).toISOString(),
    },
    {
      id: 'rel_105',
      jobId: 'J-105',
      instrumentId: 'item_088',
      cycleCompleted: true,
      packagingAcceptable: false,
      indicatorVerified: true,
      releaseDecision: 'QUARANTINED',
      notes: 'Packaging tear detected on lateral seal.',
      releasedBy: 'QA Inspector - Elena Rostova',
      releasedAt: new Date(now.getTime() - 1 * 3600000).toISOString(),
    },
  ];

  // 14. CSSD Audit Item Events
  const cssd_item_events: CSSDItemEvent[] = [
    {
      id: 'cie_01',
      itemId: 'item_021',
      jobId: 'J-101',
      eventType: 'STERILIZATION_RELEASED',
      fromStatus: 'RELEASE_PENDING',
      toStatus: 'STERILE',
      actorId: 'usr_cssd_01',
      actorName: 'CSSD Supervisor - Sarah Connor',
      timestamp: new Date(now.getTime() - 2.5 * 3600000).toISOString(),
      notes: 'Item released to sterile inventory Shelf A-3',
    },
    {
      id: 'cie_02',
      itemId: 'item_104',
      jobId: 'J-102',
      eventType: 'STERILIZATION_JOB_CREATED',
      fromStatus: 'RETURNED_TO_CSSD',
      toStatus: 'QUEUED',
      actorId: 'usr_ot_03',
      actorName: 'OT-03 Scrub Tech',
      timestamp: new Date(now.getTime() - 45 * 60000).toISOString(),
      notes: 'Submitted for sterilization cycle CYC-STEAM-106',
    },
    {
      id: 'cie_03',
      itemId: 'item_005',
      jobId: 'J-103',
      eventType: 'STERILIZATION_STARTED',
      fromStatus: 'QUEUED',
      toStatus: 'PROCESSING',
      actorId: 'usr_cssd_02',
      actorName: 'CSSD Specialist Adams',
      timestamp: new Date(now.getTime() - 15 * 60000).toISOString(),
      notes: 'VHP Plasma cycle CYC-PLASMA-04 started',
    },
  ];

  return {
    users,
    passwordHashes,
    operating_theatres,
    patients,
    patient_readiness,
    surgeries,
    cssd_packs,
    cssd_items,
    cssd_sterilization_jobs,
    cssd_cycle_profiles,
    cssd_releases,
    cssd_item_events,
    alerts,
    workflow_events,
    transfers,
    audit_logs,
  };
}
